# Generated by Django 3.0.9 on 2021-04-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0008_auto_20190219_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('NEW', 'New, not yet processed'), ('UNREGISTERED', 'Email not registered'), ('REGISTERED', 'Email is registered'), ('NOPDF', 'No PDF statement attached'), ('UNENCRYPTFAILED', 'Could not unencrypt'), ('UNENCRYPTED', 'Unencryption successful'), ('EXTRACTFAILED', 'Extraction failed'), ('EXTRACTED', 'Extraction success')], default='NEW', max_length=255, verbose_name='Status'),
        ),
    ]
